apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helpme-green

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: localhost:32000/helpme-green
    newTag: f945d3c-amd64
